Using intermediate certificate for update bundle signing as this reflects better how we structure the PKI

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -59,12 +59,15 @@ jobs:
         env:
           RELEASE_SIGNING_KEY_B64: ${{ secrets.RELEASE_SIGNING_KEY_B64 }}
           RELEASE_SIGNING_CERT_B64: ${{ secrets.RELEASE_SIGNING_CERT_B64 }}
+          RELEASE_SIGNING_CA_CERT: ${{ secrets.RELEASE_SIGNING_CA_CERT }}
         run: |
           [ -z "$RELEASE_SIGNING_KEY_B64" ] && echo "Signing key is missing" && exit 1
           [ -z "$RELEASE_SIGNING_CERT_B64" ] && echo "Signing cert is missing" && exit 1
+          [ -z "$RELEASE_SIGNING_CA_CERT" ] && echo "Signing CA cert is missing" && exit 1
           mkdir -p buildroot/output/images/
           echo $RELEASE_SIGNING_KEY_B64 | base64 -d > buildroot/output/images/cbpifw-update.key
           echo $RELEASE_SIGNING_CERT_B64 | base64 -d > buildroot/output/images/cbpifw-update.pem
+          echo $RELEASE_SIGNING_CA_CERT | base64 -d > buildroot/output/images/cbpifw-ca.pem
           cat buildroot/output/images/cbpifw-update.pem
           openssl x509 -in buildroot/output/images/cbpifw-update.pem -text
 
